 "use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function BookingForm({services,packages,selectedService,selectedPackage}:{services:any[];packages:any[];selectedService?:string;selectedPackage?:string}) {
 const router=useRouter(); const [loading,setLoading]=useState(false); const [done,setDone]=useState<any>(null); const [error,setError]=useState("");
 const [form,setForm]=useState<any>({serviceId:selectedService||"",packageId:selectedPackage||"",eventType:"Wedding",eventName:"",eventDate:"",guests:"",venue:"",address:"",city:"",area:"",locationDetails:"",name:"",phone:"",email:"",whatsapp:"",decoration:"",catering:"",photography:"",stage:"",lighting:"",specialInstructions:""});
 const set=(e:any)=>setForm({...form,[e.target.name]:e.target.value});
 async function submit(e:any){e.preventDefault();setLoading(true);setError("");try{const r=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not submit");setDone(d);router.push(`/booking?success=${d.reference}`)}catch(x:any){setError(x.message)}finally{setLoading(false)}}
 return <div className="form-card">{error&&<div className="alert">{error}</div>}<form onSubmit={submit}><div className="form-grid">
 <div className="field"><label>Full Name *</label><input required name="name" value={form.name} onChange={set}/></div><div className="field"><label>Phone Number *</label><input required name="phone" value={form.phone} onChange={set}/></div>
 <div className="field"><label>Email Address *</label><input required type="email" name="email" value={form.email} onChange={set}/></div><div className="field"><label>WhatsApp Number</label><input name="whatsapp" value={form.whatsapp} onChange={set}/></div>
 <div className="field"><label>Event Type *</label><select name="eventType" value={form.eventType} onChange={set}>{["Wedding","Birthday","Corporate","Engagement","Conference","Seminar","Bridal Shower","Private Party","Custom Event"].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="field"><label>Event Name *</label><input required name="eventName" value={form.eventName} onChange={set} placeholder="e.g. Hamza & Sara Wedding"/></div>
 <div className="field"><label>Event Date *</label><input required type="date" name="eventDate" value={form.eventDate} onChange={set}/></div><div className="field"><label>Expected Guests *</label><input required type="number" min="1" name="guests" value={form.guests} onChange={set}/></div>
 <div className="field"><label>Preferred Package</label><select name="packageId" value={form.packageId} onChange={set}><option value="">Select package</option>{packages.map(p=><option value={p.id} key={p.id}>{p.name} — PKR {p.price.toLocaleString()}</option>)}</select></div>
 <div className="field"><label>Required Service</label><select name="serviceId" value={form.serviceId} onChange={set}><option value="">Select service</option>{services.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div>
 <div className="field"><label>Event Venue *</label><input required name="venue" value={form.venue} onChange={set}/></div><div className="field"><label>City *</label><input required name="city" value={form.city} onChange={set}/></div>
 <div className="field"><label>Complete Address *</label><input required name="address" value={form.address} onChange={set}/></div><div className="field"><label>Area *</label><input required name="area" value={form.area} onChange={set}/></div>
 <div className="field full"><label>Additional Location Details</label><textarea name="locationDetails" value={form.locationDetails} onChange={set}/></div>
 {["decoration","catering","photography","stage","lighting"].map(x=><div className="field" key={x}><label>{x[0].toUpperCase()+x.slice(1)} Requirements</label><input name={x} value={form[x]} onChange={set}/></div>)}
 <div className="field full"><label>Special Instructions</label><textarea name="specialInstructions" value={form.specialInstructions} onChange={set}/></div>
 <div className="field full"><button className="btn btn-gold" disabled={loading}>{loading?"Submitting…":"Submit Booking Request"}</button></div>
 </div></form></div>
}

export function ContactForm(){const [f,setF]=useState<any>({name:"",email:"",phone:"",subject:"",message:""});const [msg,setMsg]=useState("");const [err,setErr]=useState("");async function go(e:any){e.preventDefault();setErr("");setMsg("");const r=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});const d=await r.json();if(r.ok){setMsg("Thanks! Your inquiry has been received.");setF({name:"",email:"",phone:"",subject:"",message:""})}else setErr(d.error||"Something went wrong.")}return <div className="form-card">{msg&&<div className="alert">{msg}</div>}{err&&<div className="alert">{err}</div>}<form onSubmit={go}><div className="form-grid"><div className="field"><label>Name *</label><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></div><div className="field"><label>Email *</label><input required type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></div><div className="field"><label>Phone</label><input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></div><div className="field"><label>Subject *</label><input required value={f.subject} onChange={e=>setF({...f,subject:e.target.value})}/></div><div className="field full"><label>Message *</label><textarea required value={f.message} onChange={e=>setF({...f,message:e.target.value})}/></div><div className="field full"><button className="btn btn-primary">Send Inquiry</button></div></div></form></div>}
